name: Build TypeScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This should already be the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # This should also already be the latest version
        with:
          node-version: '20'  # Use Node.js version 20

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Upload Compiled Files
        uses: actions/upload-artifact@v3  # Ensure this is using the latest version
        with:
          name: compiled-files
          path: dist/
