name: Build TypeScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0  # Specify the latest patch version

      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1  # Specify the latest patch version
        with:
          node-version: '20'  # Use Node.js version 20

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Upload Compiled Files
        uses: actions/upload-artifact@v3.1.2  # Specify the latest patch version
        with:
          name: compiled-files
          path: dist/
