name: Validate with HACS

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate_hacs:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Valiate With HACS
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: HACS validation
        uses: 'hacs/action@main'
        with:
          CATEGORY: 'plugin'

  # validate_hassfest:
  #   name: Validate with Hassfest
  #   runs-on: "ubuntu-latest"
  #   steps:
  #       - uses: "actions/checkout@v4"
  #       - uses: "home-assistant/actions/hassfest@master"
